name: gcep-fabric-network
version: "2.0.0"
caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: gcepchannel
    contracts:
      - id: gcep
        version: "1.0"

organizations:
  - mspid: HospitalMSP
    identities:
      certificates:
        - name: hospital-admin
          clientPrivateKey:
            path: ./crypto-config/peerOrganizations/hospital.gcep.local/users/Admin@hospital.gcep.local/msp/keystore/key.pem
          clientSignedCert:
            path: ./crypto-config/peerOrganizations/hospital.gcep.local/users/Admin@hospital.gcep.local/msp/signcerts/Admin@hospital.gcep.local-cert.pem
    connectionProfile:
      path: ./crypto-config/connection-profiles/hospital.yaml
      discover: true

  - mspid: RegulatorMSP
    identities:
      certificates:
        - name: regulator-admin
          clientPrivateKey:
            path: ./crypto-config/peerOrganizations/regulator.gcep.local/users/Admin@regulator.gcep.local/msp/keystore/key.pem
          clientSignedCert:
            path: ./crypto-config/peerOrganizations/regulator.gcep.local/users/Admin@regulator.gcep.local/msp/signcerts/Admin@regulator.gcep.local-cert.pem
    connectionProfile:
      path: ./crypto-config/connection-profiles/regulator.yaml
      discover: true
